import pygame
pygame.mixer.init()
#Fish
cod = pygame.image.load("resource/fish/cod.png")
salmon = pygame.image.load("resource/fish/salmon.png")
redsnapper = pygame.image.load("resource/fish/red snapper.png")
bass = pygame.image.load("resource/fish/bass.png")
flounder = pygame.image.load("resource/fish/flounder.png")
clownfish = pygame.image.load("resource/fish/clownfish.png")
koi = pygame.image.load("resource/fish/koi.png")
tuna = pygame.image.load("resource/fish/tuna.png")
mackeral = pygame.image.load("resource/fish/mackeral.png")
carp = pygame.image.load("resource/fish/carp.png")
arapaima = pygame.image.load("resource/fish/arapaima.png")
surgeon = pygame.image.load("resource/fish/tangfish.png")
rederring = pygame.image.load("resource/fish/redherring.png")
barb = pygame.image.load("resource/fish/barb.png")
maomao = pygame.image.load("resource/fish/maomao.png")
sardine = pygame.image.load("resource/fish/sardine.png")
tilapia = pygame.image.load("resource/fish/tilapia.png")
#UI
fisherdude = pygame.image.load("resource/ui/fisherdude.png")
fishbutton = pygame.image.load("resource/ui/fishbutton.png")
youcaught = pygame.image.load("resource/ui/youcaught.png")
stopwatch = pygame.image.load("resource/ui/cooltimer.png")
upgraderod = pygame.image.load("resource/ui/upgraderod.png")
upgradeloaction = pygame.image.load("resource/ui/upgradelocation.png")
arrow = pygame.image.load("resource/ui/arrow.png")
saveicon = pygame.image.load('resource/ui/savebutton.png')
bar = pygame.image.load("resource/ui/bar.png")
#Music
upgradesound = pygame.mixer.Sound("resource/sound/upgradesound.mp3")
chaching = pygame.mixer.Sound("resource/sound/money.mp3")
splash = pygame.mixer.Sound("resource/sound/splash.mp3")
music = pygame.mixer.Sound("resource/sound/gentle-backgroundmusic.mp3")
cheatson = pygame.mixer.Sound("resource/sound/cheatson.mp3")
cheatdisabled = pygame.mixer.Sound("resource/sound/cheatsdisabled.mp3")
